# Generated by Django 5.0.7 on 2024-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('adress', models.TextField(blank=True, default=None, null=True)),
                ('motes', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
