# Generated by Django 5.0.7 on 2024-07-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacs',
            new_name='Contact',
        ),
    ]
