# Generated by Django 5.0.7 on 2024-07-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_contacs_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='motes',
            new_name='notes',
        ),
    ]
