# Generated by Django 5.0.7 on 2024-07-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_motes_contact_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='address',
        ),
    ]
