# Generated by Django 5.0.7 on 2024-07-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_created_at_contact_sex_contact_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m'),
        ),
    ]
