# Generated by Django 5.0.7 on 2024-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
