# Generated by Django 5.0.7 on 2024-08-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other')], default='man', max_length=10, verbose_name='sex'),
        ),
    ]
